---
name: Test RouteGen Python Script

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Set up python 3.9
        uses: actions/setup-python@v4
        with:
          # DCS systems use 3.6.8
          python-version: '3.9'
      - name: run py
        run: python3 ./scripts/python/route_gen_moon_board.py 5
